<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Slim</h1>
        <div>a microframework for PHP</div>

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>
        <?php endif; ?>
        <h2>SELECT</h2>
        <form action="./select" method="POST">
            <input type="text" name="slimsql-api-token" />
            <textarea name="sql">select * from person;
            </textarea><br>
            <input type="submit" />
        </form>

        <h2>CREATE TABLE</h2>
        <form action="./exec" method="POST">
            <input type="text" name="slimsql-api-token" />
            <textarea name="sql">CREATE TABLE IF NOT EXISTS person(
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(10),
                age INTEGER
            )
            </textarea><br>
            <input type="submit" />
        </form>

        <h2>INSERT</h2>
        <form action="./insert" method="POST">
            <input type="text" name="slimsql-api-token" />
            <textarea name="sql">INSERT INTO person(name, age) VALUES ('mike', 30)
            </textarea><br>
            <input type="submit" />
        </form>
    </body>
</html>
